chore: move over the helm chart for the ui from the operator repo
konveyor/move2kube-operator pull request #55
Opened 2022-01-03 23:15 UTC by HarikrishnanBalagopal

Signed-off-by: Harikrishnan Balagopal <harikrishmenon@gmail.com>

2022-01-03 23:24 UTC, ashokponkumar requested changes
Won't we need a copy of the helm chart here retained till the new operator is in place? Otherwise the current helm based operator is not valid. So we can only remove the GitHub action part alone. Also from operator perspective, in read me, the helm chart reference can possible be removed.

2022-01-03 23:43 UTC, ashokponkumar commented
Also the prepare for release section from mahespur might need to be removed

2022-01-03 23:44 UTC, HarikrishnanBalagopal commented
> Also the prepare for release section from mahespur might need to be removed

done

2022-01-03 23:49 UTC, HarikrishnanBalagopal commented
> Won't we need a copy of the helm chart here retained till the new operator is in place? Otherwise the current helm based operator is not valid. So we can only remove the GitHub action part alone. Also from operator perspective, in read me, the helm chart reference can possible be removed.

aren't the release tar files enough?

2022-01-03 23:50 UTC, ashokponkumar commented
The operator Dockerfile uses the helm chart from its context (the operator repo).

2022-01-03 23:54 UTC, HarikrishnanBalagopal commented
> The operator Dockerfile uses the helm chart from its context (the operator repo).

I commented that out https://github.com/konveyor/move2kube-operator/pull/55/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R6

2022-01-03 23:56 UTC, ashokponkumar commented
> > The operator Dockerfile uses the helm chart from its context (the operator repo).
> 
> I commented that out https://github.com/konveyor/move2kube-operator/pull/55/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R6

Yes, that line is required. Without it, the operator does nothing.

2022-01-04 00:00 UTC, HarikrishnanBalagopal commented
> > > The operator Dockerfile uses the helm chart from its context (the operator repo).
> > 
> > 
> > I commented that out https://github.com/konveyor/move2kube-operator/pull/55/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R6
> 
> Yes, that line is required. Without it, the operator does nothing.

yes, but isn't it broken anyway?

2022-01-04 00:02 UTC, ashokponkumar commented
We have not tested it extensively with the new UI. But technically, it should be working, since the operator does nothing but the equivalent of a helm install

2022-01-04 09:28 UTC, ashokponkumar requested changes

2022-01-04 09:28 UTC, ashokponkumar commented on Makefile
>  	helm upgrade --install --set image_tag=${IMAGE_TAG} ${RELEASE_NAME} helm-charts/move2kube/
Do we want to remove this section too?

2022-01-04 10:01 UTC, HarikrishnanBalagopal commented on Makefile
>  	helm upgrade --install --set image_tag=${IMAGE_TAG} ${RELEASE_NAME} helm-charts/move2kube/
let's retain it

2022-01-04 10:23 UTC, ashokponkumar approved these changes

2022-01-04 10:23 UTC, merged